server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /app;
    index index.php index.html index.htm;

    # Wichtig für Archivarix CSS, JS und Bilder
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP-FPM Anbindung für Nixpacks
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
