events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen ${PORT};
        root /app;
        index index.php index.html;

        # Das ist die magische Regel für Archivarix:
        # Alles, was nicht physisch existiert, wird an die index.php übergeben
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # PHP-FPM Weiterleitung für Nixpacks
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
